questions =  [
    {"id": 0, "question": "I'm excited to check my underwear after farting.", "effects": {"wet": 1}},
    {"id": 1, "question": "A fart that leaves no mark as its legacy is worthless.", "effects": {"wet": 1}},
    {"id": 2, "question": "I enjoy the warmth of fart liquid.", "effects": {"wet": 1}},
    {"id": 3, "question": "All of my underwear have brown stains.", "effects": {"wet": 1}},
    {"id": 8, "question": "Wet farts are just poop.", "effects": {"wet": -1}},
    {"id": 9, "question": "Cleaning up a wet fart is more trouble than it's worth.", "effects": {"wet": -1}},
    {"id": 10, "question": "I always change after a wet fart.", "effects": {"wet": -1}},
    {"id": 11, "question": "I often go to the toilet to fart in case it's more than just a fart.", "effects": {"wet": -1}},
    {"id": 15, "question": "The more people who smell a fart, the better.", "effects": {"smelly": 1}},
    {"id": 16, "question": "A fart that doesn't smell may as well not be a fart at all.", "effects": {"smelly": 1}},
    {"id": 17, "question": "I like the lingering odor of a fart.", "effects": {"smelly": 1}},
    {"id": 18, "question": "<span>I often Dutch oven<sup class='help' title='Trapping a fart under a cover to inhale it.'>?</sup> myself.</span>", "effects": {"smelly": 1}},
    {"id": 23, "question": "A fart's smell should be known only to the farter.", "effects": {"smelly": -1}},
    {"id": 24, "question": "The smell of my own farts disgust me.", "effects": {"smelly": -1}},
    {"id": 25, "question": "The smell of other people's farts disgust me.", "effects": {"smelly": -1}},
    {"id": 26, "question": "If I wanted to smell shit, I'd just go to the bathroom.", "effects": {"smelly": -1}},
    {"id": 30, "question": "Noisy farts ruin the surprise.", "effects": {"silent": 1}},
    {"id": 31, "question": "It's embarrassing when people hear me fart.", "effects": {"silent": 1}},
    {"id": 32, "question": "I negatively judge those who fart loudly in public.", "effects": {"silent": 1}},
    {"id": 33, "question": "I prefer slowly, quietly allowing air to escape.", "effects": {"silent": 1}},
    {"id": 38, "question": "I like being able to feel the breeze from a fart.", "effects": {"silent": -1}},
    {"id": 39, "question": "I like everyone to know it was me who farted.", "effects": {"silent": -1}},
    {"id": 40, "question": "The noise is half of the fun.", "effects": {"silent": -1}},
    {"id": 41, "question": "I angle myself to make the noisiest fart possible.", "effects": {"silent": -1}}
];